### ISSUE TITLE
Actionbar text always displays values for the spells on the first action bar

### ISSUE THREAD

**Issue by CaleG** [coolmodi/SpellCalc#19] opened 2020-09-16 19:32 UTC
In the default UI the action bar text will only show the value for the spell on the first action bar even if you switch it to display any of the other bars.

**Comment by coolmodi** [comment] 2020-09-19 01:11
Only paging for druid forms on bar 1 is supported right now.

**Comment by coolmodi** [comment] 2020-09-19 01:12
Duplicate of #15

**Closed by coolmodi** 2020-09-19 01:12 UTC
