### ISSUE TITLE
Fails to load any button text

### ISSUE THREAD

**Issue by Viridz** [coolmodi/SpellCalc#28] opened 2021-06-07 07:25 UTC
Message: ...terface\AddOns\SpellCalc\UI/actionbar/buttonText.lua:51: attempt to index local 'buttonFrame' (a nil value)
Time: Mon Jun  7 00:24:11 2021
Count: 1
Stack: ...terface\AddOns\SpellCalc\UI/actionbar/buttonText.lua:51: attempt to index local 'buttonFrame' (a nil value)
[string "@Interface\AddOns\SpellCalc\UI/actionbar/buttonText.lua"]:51: in function <...terface\AddOns\SpellCalc\UI/actionbar/buttonText.lua:50>
[string "@Interface\AddOns\SpellCalc\UI/actionbar/buttonText.lua"]:82: in function <...terface\AddOns\SpellCalc\UI/actionbar/buttonText.lua:74>
[string "@Interface\AddOns\SpellCalc\UI/actionbar/buttonText.lua"]:179: in function `SetupActionButtonText'
[string "@Interface\AddOns\SpellCalc\UI/actionbar/ActionBarValues.lua"]:339: in function `Setup'
[string "@Interface\AddOns\SpellCalc\events.lua"]:31: in function `?'
[string "@Interface\AddOns\SpellCalc\events.lua"]:146: in function <Interface\AddOns\SpellCalc\events.lua:145>

Locals: buttonFrame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'buttonFrame' (a nil value)"
SetIsHeal = <function> defined @Interface\AddOns\SpellCalc\UI/actionbar/buttonText.lua:39
UpdatePosition = <function> defined @Interface\AddOns\SpellCalc\UI/actionbar/buttonText.lua:29

**Comment by coolmodi** [comment] 2021-06-08 14:24
I tried it with the latest Dominos version (9.0.28-bcc) and it works fine for me. Can you disable _all_ other addons and see if the error still occurs? If not check with just this addon and Dominos active.

**Comment by Viridz** [comment] 2021-06-08 19:02
Correct yeah. Only two addons enabled.

**Comment by Viridz** [comment] 2021-06-08 19:23
Moving spells to a blizzard action bar fixed the problem.

**Comment by coolmodi** [comment] 2021-06-08 19:51
Not sure what causes the problem for you, it should work fine with Dominos. I tried various settings and couldn't reproduce the error. I'll try fiddling around with it some more when I have time

**Comment by FlameN88** [comment] 2022-01-12 17:35
This issue also happens to me, no button text displays (I still get mouse-over text correctly). The issue only happens on my paladin with dominos enabled (shadow priest button text display correctly).

**Comment by Talimar** [comment] 2022-05-02 15:50
I also get errors with Dominos enabled.

1x SpellCalc\UI/actionbar/buttonText.lua:51: attempt to index local 'buttonFrame' (a nil value)
[string "@SpellCalc\UI/actionbar/buttonText.lua"]:51: in function <SpellCalc\UI/actionbar/buttonText.lua:50>
[string "@SpellCalc\UI/actionbar/buttonText.lua"]:82: in function <SpellCalc\UI/actionbar/buttonText.lua:74>
[string "@SpellCalc\UI/actionbar/buttonText.lua"]:179: in function `SetupActionButtonText'
[string "@SpellCalc\UI/actionbar/ActionBarValues.lua"]:339: in function `Setup'
[string "@SpellCalc\events.lua"]:31: in function `?'
[string "@SpellCalc\events.lua"]:146: in function <SpellCalc\events.lua:145>

Locals:
buttonFrame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'buttonFrame' (a nil value)"
SetIsHeal = <function> defined @SpellCalc\UI/actionbar/buttonText.lua:39
UpdatePosition = <function> defined @SpellCalc\UI/actionbar/buttonText.lua:29




36x ...ceSpellCalc\UI/actionbar/ActionBarValues.lua:177: attempt to index upvalue 'buttonText' (a nil value)
[string "@SpellCalc\UI/actionbar/ActionBarValues.lua"]:177: in function <...ceSpellCalc\UI/actionbar/ActionBarValues.lua:176>
[string "@SpellCalc\UI/actionbar/ActionBarValues.lua"]:205: in function `SlotUpdate'
[string "@SpellCalc\events.lua"]:101: in function `?'
[string "@SpellCalc\events.lua"]:146: in function <SpellCalc\events.lua:145>

Locals:
slot = 120
spellId = 23161
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'buttonText' (a nil value)"
spellsInBar = <table> {
}
buttonText = nil
_addon = <table> {
 IsBooleanFlagActive = <function> defined @SpellCalc\system/aura.lua:316
 CostHandler = <table> {
 }
 UpdateSpellPower = <function> defined @SpellCalc\system/stats.lua:154
 spellClassSet = <table> {
 }
 UpdateRecievedItemData = <function> defined @SpellCalc\system/items.lua:66
 PrintDebug = <function> defined @SpellCalc\helper.lua:85
 effectHandler = <table> {
 }
 BUFF_CONDITIONS = <table> {
 }
 CREATURE_TYPE = <table> {
 }
 ClassSettings = <function> defined @SpellCalc\data/classes/warlock.lua:247
 WEAPON_SUBCLASS = <table> {
 }
 UpdateAttackDmg = <function> defined @SpellCalc\system/stats.lua:270
 npcResistances = <table> {
 }
 spellRankInfo = <table> {
 }
 JUDGEMENT_ID = 20271
 GetShapeshiftName = <function> defined @SpellCalc\helper.lua:40
 UpdateWeaponRestrictedAuras = <function> defined @SpellCalc\system/aura.lua:229
 UpdateAttackSpeeds = <function> defined @SpellCalc\system/stats.lua:242
 IsOffHandWeaponEquipped = <function> defined @SpellCalc\system/items.lua:240
 ApplyAuraEffect = <function> defined @SpellCalc\system/aura.lua:294
 PrintSuccess = <function> defined @SpellCalc\helper.lua:52
 WEAPON_TYPES_MASK = <table> {
 }
 TriggerUpdate = <function> defined @SpellCalc\core/core.lua:724
 aurasTarget = <table> {
 }
 GetCalcedSpell = <function> defined @SpellCalc\core/core.lua:754
 SPELL_EFFECT_FLAGS = <table> {
 }
 events = <table> {
 }
 UpdatePlayerAuras = <function> defined @SpellCalc\system/playerAuras.lua:48
 FullUpdate = <function> defined @SpellCalc\system/stats.lua:314
 SCHOOL_MASK = <table> {
 }
 RemoveTableEntry = <function> defined @SpellCalc\helper.lua:9
 stats = <table> {
 }
 UpdateTalents = <function> defined @SpellCalc\system/talents.lua:8
 AddLocalization = <function> defined @SpellCalc\i18n/loc.lua:13
 talentData = <table> {
 }
 BOOLEAN_FLAGS = <table> {
 }
 UpdateManaRegen = <function> defined @SpellCalc\system/stats.lua:214
 UpdateWeaponEnchants = <function> defined @SpellCalc\system/weaponEnchants.lua:49
 ActionBarValues = <table> {
 }
 SetupActionButtonText = <function> defined @SpellCalc\UI/actionbar/buttonText.lua:125
 UpdateRangedAttackDmg = <function> defined @SpellCalc\system/stats.lua:277
 IsMainHandWeaponEquipped = <function> defined @SpellCalc\system/items.lua:235
 CombatRatingUpdate = <function> defined @SpellCalc\system/stats.lua:289
 GetCurrentSpellData = <function> defined @SpellCalc\core/core.lua:771
 levelDefaultArmor = <table> {
 }
 GetEffectiveManaPool = <function> defined @SpellCalc\core/core.lua:138
 PrintWarn = <function> defined @SpellCalc\helper.lua:64
 SPELL_EFFECT_TYPES = <table> {
 }
 RemoveAuraEffect = <function> defined @SpellCalc\system/aura.lua:306
 UpdateItems = <function> defined @SpellCalc\system/items.lua:166
 NewCalcedSpell = <function> defined @SpellCalc\core/CalcedSpell.lua:229
 MagicCalc = <table> {
 }
 MeleeCalc = <table> {
 }
 Target = <table> {
 }
 SPELL_AURA_TYPES = <table> {
 }
 PrintTable = <function> defined @SpellCalc\helper.lua:71
 IsOneHandEquipped = <function> defined @SpellCalc\system/items.lua:230
 IsDualWieldEquipped = <function> defined @SpellCalc\system/items.lua:271
 IsWeaponTypeMaskEquipped = <function> defined @SpellCalc\system/items.lua:256
 IsWeaponTypeEquipped = <func

**Comment by Talimar** [comment] 2022-05-23 13:33
Tried again. Slightly different error this time. Using bcc version yes. Old error also still present.

Could it be macros it doesn't like? The error counter goes up every time I hit a modifier like ctrl or shift.

180x ...ceSpellCalc\UI/actionbar/ActionBarValues.lua:177: attempt to index upvalue 'buttonText' (a nil value)
[string "@SpellCalc\UI/actionbar/ActionBarValues.lua"]:177: in function <...ceSpellCalc\UI/actionbar/ActionBarValues.lua:176>
[string "@SpellCalc\UI/actionbar/ActionBarValues.lua"]:207: in function `SlotUpdate'
[string "@SpellCalc\events.lua"]:101: in function `?'
[string "@SpellCalc\events.lua"]:146: in function <SpellCalc\events.lua:145>

Locals:
slot = 1
spellId = 688
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'buttonText' (a nil value)"
spellsInBar = <table> {
}
buttonText = nil
_addon = <table> {
 IsBooleanFlagActive = <function> defined @SpellCalc\system/aura.lua:316
 CostHandler = <table> {
 }
 UpdateSpellPower = <function> defined @SpellCalc\system/stats.lua:154
 spellClassSet = <table> {
 }
 UpdateRecievedItemData = <function> defined @SpellCalc\system/items.lua:66
 PrintDebug = <function> defined @SpellCalc\helper.lua:85
 effectHandler = <table> {
 }
 BUFF_CONDITIONS = <table> {
 }
 CREATURE_TYPE = <table> {
 }
 ClassSettings = <function> defined @SpellCalc\data/classes/warlock.lua:247
 WEAPON_SUBCLASS = <table> {
 }
 UpdateAttackDmg = <function> defined @SpellCalc\system/stats.lua:270
 npcResistances = <table> {
 }
 spellRankInfo = <table> {
 }
 JUDGEMENT_ID = 20271
 GetShapeshiftName = <function> defined @SpellCalc\helper.lua:40
 UpdateWeaponRestrictedAuras = <function> defined @SpellCalc\system/aura.lua:229
 UpdateAttackSpeeds = <function> defined @SpellCalc\system/stats.lua:242
 IsOffHandWeaponEquipped = <function> defined @SpellCalc\system/items.lua:240
 ApplyAuraEffect = <function> defined @SpellCalc\system/aura.lua:294
 PrintSuccess = <function> defined @SpellCalc\helper.lua:52
 WEAPON_TYPES_MASK = <table> {
 }
 TriggerUpdate = <function> defined @SpellCalc\core/core.lua:724
 aurasTarget = <table> {
 }
 GetCalcedSpell = <function> defined @SpellCalc\core/core.lua:754
 SPELL_EFFECT_FLAGS = <table> {
 }
 events = <table> {
 }
 UpdatePlayerAuras = <function> defined @SpellCalc\system/playerAuras.lua:48
 FullUpdate = <function> defined @SpellCalc\system/stats.lua:314
 SCHOOL_MASK = <table> {
 }
 RemoveTableEntry = <function> defined @SpellCalc\helper.lua:9
 stats = <table> {
 }
 UpdateTalents = <function> defined @SpellCalc\system/talents.lua:8
 AddLocalization = <function> defined @SpellCalc\i18n/loc.lua:13
 talentData = <table> {
 }
 BOOLEAN_FLAGS = <table> {
 }
 UpdateManaRegen = <function> defined @SpellCalc\system/stats.lua:214
 UpdateWeaponEnchants = <function> defined @SpellCalc\system/weaponEnchants.lua:49
 ActionBarValues = <table> {
 }
 SetupActionButtonText = <function> defined @SpellCalc\UI/actionbar/buttonText.lua:125
 UpdateRangedAttackDmg = <function> defined @SpellCalc\system/stats.lua:277
 IsMainHandWeaponEquipped = <function> defined @SpellCalc\system/items.lua:235
 CombatRatingUpdate = <function> defined @SpellCalc\system/stats.lua:289
 GetCurrentSpellData = <function> defined @SpellCalc\core/core.lua:771
 levelDefaultArmor = <table> {
 }
 GetEffectiveManaPool = <function> defined @SpellCalc\core/core.lua:138
 PrintWarn = <function> defined @SpellCalc\helper.lua:64
 SPELL_EFFECT_TYPES = <table> {
 }
 RemoveAuraEffect = <function> defined @SpellCalc\system/aura.lua:306
 UpdateItems = <function> defined @SpellCalc\system/items.lua:166
 NewCalcedSpell = <function> defined @SpellCalc\core/CalcedSpell.lua:229
 MagicCalc = <table> {
 }
 MeleeCalc = <table> {
 }
 Target = <table> {
 }
 SPELL_AURA_TYPES = <table> {
 }
 PrintTable = <function> defined @SpellCalc\helper.lua:71
 IsOneHandEquipped = <function> defined @SpellCalc\system/items.lua:230
 IsDualWieldEquipped = <function> defined @SpellCalc\system/items.lua:271
 IsWeaponTypeMaskEquipped = <function> defined @SpellCalc\system/items.lua:256
 IsWeaponTypeEquipped = <function

**Comment by coolmodi** [comment] 2022-06-09 08:30
Should be fixed now in 0.16

**Closed by coolmodi** 2022-06-09 08:30 UTC
